### PR TITLE
A11y Automation

### PR DESCRIPTION
**Pull request by SiddPatki**
Enabled a11y automation flags in the YML file

### CODE REVIEW

**Comment by SiddPatki** [comment]
@princebaretto99  Can you please review this PR?
This will enable teams to launch a11y builds from Jenkins.

**Review by samirans89 — APPROVED** [review]

**Comment by samirans89** [comment]
please resolve conflicts in the PR

image

**Review by samirans89 — CHANGES_REQUESTED** [review]
Please resolve merge conflicts in the PR

**Review by princebaretto99 — APPROVED** [review]
LGTM. Please resolve the conflicts and merge.

**Comment by SiddPatki** [comment]
After some digging, I found we don't need this branch to be merged as their exists a different branch with all these changes already.
Thanks
Closing this PR.

**Pull request closed without merging**
